== Core Profile Definition

This chapter defines the contents of the Jakarta™ EE 10.0 Core Profile.

[[required_components]]
=== Required Components

The following technologies are required components of the Core Profile:

* Jakarta Annotations 2.1
* Jakarta Contexts and Dependency Injection (CDI) 4.0 (CDI Lite section)
* Jakarta Dependency Injection 2.0
* Jakarta Interceptors 2.1
* Jakarta JSON Processing 2.1
* Jakarta JSON Binding 3.0
* Jakarta RESTful Web Services 3.1

=== Optional Components

The optional Jakarta XML Binding support in Jakarta RESTful Web Services implementations is not required for the Core Profile.

Jakarta Expression Language support is not required in  Jakarta Contexts and Dependency Injection Lite implementations since this is part of the Full CDI specification.

The Java SE section of the CDI 4.0 are not required for Core Profile implementations. This is because that specification states that CDI implementations that support the Java SE API are required to support the Full version of the CDI specification.

[[additional_requirements]]
=== Additional Requirements

There are currently no requirements on the deployment packaging of
core profile based applications.
