[appendix]
[[relateddocs]]
== Related Documents

This specification refers to the following
documents. The terms used to refer to the documents in this
specification are included in parentheses.

_Jakarta™ EE Platform Specification, Version 11.0_. Available at: _https://jakarta.ee/specifications/platform/11/_

_Java™ Platform, Standard Edition (Java SE specification), v17_. Available at: _https://www.jcp.org/en/jsr/detail?id=392_

_Java™ Platform, Standard Edition, v17 API Specification_. Available at: _https://docs.oracle.com/javase/17/docs/_

_Jakarta™ RESTful Web Services Specification, Version 4.0_. Available at: _https://jakarta.ee/specifications/restful-ws/4.0/_

_Jakarta™ Annotations Specification, Version 3.0_. Available at: _https://jakarta.ee/specifications/annotations/3.0/_

_Jakarta™ Interceptors Specification, Version 2.2_. Available at: _https://jakarta.ee/specifications/interceptors/2.2/_

_Jakarta™ Contexts and Dependency Injection Specification (CDI Lite section), Version 4.1_. Available at: _https://jakarta.ee/specifications/cdi/4.1/_

_Jakarta™ Dependency Injection Specification, Version 2.0_. Available at: _https://jakarta.ee/specifications/dependency-injection/2.0/_

_Jakarta™ JSON Processing Specification, Version 2.1_. Available at: _https://jakarta.ee/specifications/jsonp/2.1/_

_Jakarta™ JSON Binding Specification, Version 3.0_. Available at: _https://jakarta.ee/specifications/jsonb/3.0/_

_Jakarta™ EE Working Group_
(_https://jakarta.ee/about/working-group/_)