[appendix]
[[relateddocs]]
== Related Documents

This specification refers to the following
documents. The terms used to refer to the documents in this
specification are included in parentheses.

_Jakarta™ EE Core Profile Specification, Version 11.0_. Available at: _https://jakarta.ee/specifications/coreprofile/11/_

_Jakarta™ EE Platform Specification, Version 11.0_. Available at: _https://jakarta.ee/specifications/platform/11/_

_Java™ Platform, Standard Edition (Java SE specification), v17_. Available at: _https://www.jcp.org/en/jsr/detail?id=392_

_Java™ Platform, Standard Edition, v17 API Specification_. Available at: _https://docs.oracle.com/javase/17/docs/_

_Jakarta™ Enterprise Beans Specification, Version 4.0_. Available at: _https://jakarta.ee/specifications/enterprise-beans/4.0/_

_Jakarta™ Pages Specification, Version 4.0_. Available at: _https://jakarta.ee/specifications/pages/4.0/_

_Jakarta™ Expression Language Specification, Version 6.0_. Available at: _https://jakarta.ee/specifications/expression-language/6.0/_

_Jakarta™ Servlet Specification, Version 6.1_. Available at: _https://jakarta.ee/specifications/servlet/6.1/_

_Jakarta™ Transactions Specification, Version 2.0_. Available at: _https://jakarta.ee/specifications/transactions/2.0/_

_Jakarta™ RESTful Web Services Specification, Version 4.0_. Available at: _https://jakarta.ee/specifications/restful-ws/4.0/_

_Jakarta™ Annotations Specification, Version 3.0_. Available at: _https://jakarta.ee/specifications/annotations/3.0/_

_Jakarta™ Debugging Support for Other Languages Specification, Version 2.0_. Available at: _https://jakarta.ee/specifications/debugging/2.0/_

_Jakarta™ Standard Tag Library Specification, Version 3.0_. Available at: _https://jakarta.ee/specifications/tags/3.0/_

_Jakarta™ Faces Specification, Version 4.1_. Available at: _https://jakarta.ee/specifications/faces/4.1/_

_Jakarta™ Persistence Specification, Version 3.2_. Available at: _https://jakarta.ee/specifications/persistence/3.2/_

_Jakarta™ Validation Specification, Version 3.1_. Available at: _https://jakarta.ee/specifications/bean-validation/3.1/_

_Jakarta™ Interceptors Specification, Version 2.2_. Available at: _https://jakarta.ee/specifications/interceptors/2.2/_

_Jakarta™ Contexts and Dependency Injection Specification, Version 4.1_. Available at: _https://jakarta.ee/specifications/cdi/4.1/_

_Jakarta™ Dependency Injection Specification, Version 2.0_. Available at: _https://jakarta.ee/specifications/dependency-injection/2.0/_

_Jakarta™ WebSocket Specification, Version 2.2_. Available at: _https://jakarta.ee/specifications/websocket/2.2/_

_Jakarta™ JSON Processing Specification, Version 2.1_. Available at: _https://jakarta.ee/specifications/jsonp/2.1/_

_Jakarta™ JSON Binding Specification, Version 3.0_. Available at: _https://jakarta.ee/specifications/jsonb/3.0/_

_Jakarta™ Security Specification, Version 4.0_. Available at: _https://jakarta.ee/specifications/security/4.0/_

_Jakarta™ Authentication Specification, Version 3.1_. Available at: _https://jakarta.ee/specifications/authentication/3.1/_

_Jakarta™ Concurrency Specification, Version 3.1_. Available at: _https://jakarta.ee/specifications/concurrency/3.1/_

_Jakarta™ Data Specification, Version 1.0_. Available at: _https://jakarta.ee/specifications/data/1.0/_