== Related Documents

This specification refers to the following
documents. The terms used to refer to the documents in this
specification are included in parentheses.

 _Jakarta™ Platform, Enterprise Edition
Specification Version 8_ . Available at
_http://jcp.org/en/jsr/detail?id=366_ .

 _Java™ Platform, Standard Edition, v8 API
Specification_ (Java SE specification). Available at
_http://docs.oracle.com/javase/8/docs/_ .

 _Jakarta™  Enterprise Beans Specification, Version
3.2_ (EJB specification). Available at
_http://jcp.org/en/jsr/detail?id=345_ .

 _Jakarta™ Server Pages Specification, Version 2.3_
(JSP specification). Available at _http://jcp.org/en/jsr/detail?id=245_
.

 _Jakarta Expression Language Specification, Version
3.0_ (EL specification). Available at
_http://jcp.org/en/jsr/detail?id=341_ .

 _Jakarta™ Servlet Specification, Version 4.0_
(Servlet specification). Available at
_http://jcp.org/en/jsr/detail?id=369_ .

 _Jakarta™ Transaction, Version 1.2_ (JTA
specification). Available at _http://jcp.org/en/jsr/detail?id=907_ .

JAX-RS: The Jakarta RESTful Web Services
2.1 (JAX-RS specification). Available at
_http://jcp.org/en/jsr/summary?id=370_ .

Jakarta Common Annotations for the Java Platform 1.3.
Available at _http://jcp.org/en/jsr/detail?id=250_ .

Jakarta Debugging Support for Other Languages 1.0.
Available at _http://jcp.org/en/jsr/detail?id=45_ .

Jakarta Standard Tag Library for Jakarta Server Pages 1.2
(JSTL specification). Available at _http://jcp.org/en/jsr/detail?id=52_
.

Jakarta Server Faces 2.3 (JSF specification).
Available at _http://jcp.org/en/jsr/detail?id=372_ .

Jakarta Persistence 2.2 (Jakarta Persistence
specification). Available at _http://jcp.org/en/jsr/detail?id=338_ .

Jakarta Bean Validation 2.0 (Jakarta Bean Validation
specification). Available at _http://jcp.org/en/jsr/detail?id=380_ .

Jakarta Managed Beans 1.0 (Jakarta Managed Beans
specification). Available at _http://jcp.org/en/jsr/detail?id=316_ .

Jakarta Interceptors 1.2 rev A (Interceptors
specification). Available at _http://jcp.org/en/jsr/detail?id=318_ .

Jakarta Contexts and Dependency Injection 
2.0 (CDI specification). Available at
_http://jcp.org/en/jsr/detail?id=365_ . 

Jakarta Dependency Injection 1.0 (DI
specification). Available at _http://jcp.org/en/jsr/detail?id=330_ .

 _Jakarta WebSocket 1.1_ (WebSocket
specification). Available at _http://jcp.org/en/jsr/detail?id=356_ .

 _Jakarta JSON Processing 1.1_ (JSON-P
specification). Available at _http://jcp.org/en/jsr/detail?id=374_ .

 _Jakarta JSON Binding 1.0_ (JSON-B
specification). Available at _http://jcp.org/en/jsr/detail?id=367_ .

Jakarta™ Security 1.0. Available at
_http://jcp.org/en/jsr/detail?id=375_ .

Jakarta™ Authentication 1.1 (Jakarta specification). Available at
_http://jcp.org/en/jsr/detail?id=196_ .
