== Related Documents

This specification refers to the following
documents. The terms used to refer to the documents in this
specification are included in parentheses.

_Jakarta™ EE Platform Specification Version 8. Available at: https://jakarta.ee/specifications/full-platform/8.0.1_

_Java™ Platform, Standard Edition, v8 API Specification (Java SE specification). Available at: http://docs.oracle.com/javase/8/docs/_

_Jakarta™ Enterprise Beans Specification, Version 3.2. Available at: https://jakarta.ee/specifications/enterprise-beans/2.3.2_

_Jakarta™ Server Pages Specification, Version 2.3. Available at: https://jakarta.ee/specifications/pages/2.3.4_

_Jakarta™ Expression Language Specification, Version 3.0. Available at: https://jakarta.ee/specifications/expression-language/3.0.2_

_Jakarta™ Servlet Specification, Version 4.0. Available at: https://jakarta.ee/specifications/servlet/4.0.2_

_Jakarta™ Transaction Specification, Version 1.2. Available at: https://jakarta.ee/specifications/transactions/1.3.2_

_Jakarta™ RESTful Web Services Specification, Version 2.1. Available at: https://jakarta.ee/specifications/restful-ws/2.1.5_

_Jakarta™ Annotations Specification, Version 1.3. Available at: https://jakarta.ee/specifications/annotations/1.3.4_

_Jakarta™ Debugging Support for Other Languages Specification, Version 1.0. Available at: https://jakarta.ee/specifications/debugging/1.0_

_Jakarta™ Standard Tag Library Specification, Version 1.2. Available at: https://jakarta.ee/specifications/tags/1.2.3_

_Jakarta™ Server Faces Specification, Version 2.3. Available at: https://jakarta.ee/specifications/faces/2.3.1_

_Jakarta™ Persistence Specification, Version 2.2. Available at: https://jakarta.ee/specifications/persistence/2.2.2_

_Jakarta™ Bean Validation Specification, Version 2.0. Available at: https://jakarta.ee/specifications/bean-validation/2.0_

_Jakarta™ Managed Beans Specification, Version 1.0. Available at: https://jakarta.ee/specifications/managed-beans/1.0.0_

_Jakarta™ Interceptors Specification, Version 1.2. Available at: https://jakarta.ee/specifications/interceptors/1.2.3_

_Jakarta™ Contexts and Dependency Injection Specification, Version 2.0. Available at: https://jakarta.ee/specifications/cdi/2.0_

_Jakarta™ Dependency Injection Specification, Version 1.0. Available at: https://jakarta.ee/specifications/dependency-injection/1.0_

_Jakarta™ WebSocket Specification, Version 1.1. Available at: https://jakarta.ee/specifications/websocket/1.1.1_

_Jakarta™ JSON Processing Specification, Version 1.1. Available at: https://jakarta.ee/specifications/jsonp/1.1.5_

_Jakarta™ JSON Binding Specification, Version 1.0. Available at: https://jakarta.ee/specifications/jsonb/1.0.1_

_Jakarta™ Security Specification, Version 1.0. Available at: https://jakarta.ee/specifications/security/1.0.1_

_Jakarta™ Authentication Specification, Version 1.1. Available at: https://jakarta.ee/specifications/authentication/1.1.2_
