[appendix]
[[relateddocs]]
== Related Documents

This specification refers to the following
documents. The terms used to refer to the documents in this
specification are included in parentheses.

_Jakarta™ EE Platform Specification Version 9.1_. Available at: _https://jakarta.ee/specifications/platform/9.1_

_Java™ Platform, Standard Edition, v8 API Specification (Java SE specification)_. Available at: _https://docs.oracle.com/javase/8/docs/_

_Java™ Platform, Standard Edition, v11 API Specification (Java SE specification)_. Available at: _https://docs.oracle.com/en/java/javase/11/_

_Jakarta™ Enterprise Beans Specification, Version 4.0_. Available at: _https://jakarta.ee/specifications/enterprise-beans/4.0_

_Jakarta™ Server Pages Specification, Version 3.0_. Available at: _https://jakarta.ee/specifications/pages/3.0_

_Jakarta™ Expression Language Specification, Version 4.0_. Available at: _https://jakarta.ee/specifications/expression-language/4.0_

_Jakarta™ Servlet Specification, Version 5.0_. Available at: _https://jakarta.ee/specifications/servlet/5.0_

_Jakarta™ Transaction Specification, Version 2.0_. Available at: _https://jakarta.ee/specifications/transactions/2.0_

_Jakarta™ RESTful Web Services Specification, Version 3.0_. Available at: _https://jakarta.ee/specifications/restful-ws/3.0_

_Jakarta™ Annotations Specification, Version 2.0_. Available at: _https://jakarta.ee/specifications/annotations/2.0_

_Jakarta™ Debugging Support for Other Languages Specification, Version 2.0_. Available at: _https://jakarta.ee/specifications/debugging/2.0_

_Jakarta™ Standard Tag Library Specification, Version 2.0_. Available at: _https://jakarta.ee/specifications/tags/2.0_

_Jakarta™ Server Faces Specification, Version 3.0_. Available at: _https://jakarta.ee/specifications/faces/3.0_

_Jakarta™ Persistence Specification, Version 3.0_. Available at: _https://jakarta.ee/specifications/persistence/3.0_

_Jakarta™ Bean Validation Specification, Version 3.0_. Available at: _https://jakarta.ee/specifications/bean-validation/3.0_

_Jakarta™ Managed Beans Specification, Version 2.0_. Available at: _https://jakarta.ee/specifications/managedbeans/2.0_

_Jakarta™ Interceptors Specification, Version 2.0_. Available at: _https://jakarta.ee/specifications/interceptors/2.0_

_Jakarta™ Contexts and Dependency Injection Specification, Version 3.0_. Available at: _https://jakarta.ee/specifications/cdi/3.0_

_Jakarta™ Dependency Injection Specification, Version 2.0_. Available at: _https://jakarta.ee/specifications/dependency-injection/2.0_

_Jakarta™ WebSocket Specification, Version 2.0_. Available at: _https://jakarta.ee/specifications/websocket/2.0_

_Jakarta™ JSON Processing Specification, Version 2.0_. Available at: _https://jakarta.ee/specifications/jsonp/2.0_

_Jakarta™ JSON Binding Specification, Version 2.0_. Available at: _https://jakarta.ee/specifications/jsonb/2.0_

_Jakarta™ Security Specification, Version 2.0_. Available at: _https://jakarta.ee/specifications/security/2.0_

_Jakarta™ Authentication Specification, Version 2.0_. Available at: _https://jakarta.ee/specifications/authentication/2.0_
