== Related Documents

This specification refers to the following
documents. The terms used to refer to the documents in this
specification are included in parentheses.

 _Java™ Platform, Enterprise Edition
Specification Version 8_ . Available at
_http://jcp.org/en/jsr/detail?id=366_ .

 _Java™ Platform, Standard Edition, v8 API
Specification_ (Java SE specification). Available at
_http://docs.oracle.com/javase/8/docs/_ .

 _Enterprise JavaBeans™ Specification, Version
3.2_ (EJB specification). Available at
_http://jcp.org/en/jsr/detail?id=345_ .

 _JavaServer Pages™ Specification, Version 2.3_
(JSP specification). Available at _http://jcp.org/en/jsr/detail?id=245_
.

 _Expression Language Specification, Version
3.0_ (EL specification). Available at
_http://jcp.org/en/jsr/detail?id=341_ .

 _Java™ Servlet Specification, Version 4.0_
(Servlet specification). Available at
_http://jcp.org/en/jsr/detail?id=369_ .

 _Java™ Transaction API, Version 1.2_ (JTA
specification). Available at _http://jcp.org/en/jsr/detail?id=907_ .

JAX-RS: The JavaTM API for RESTful Web Services
2.1 (JAX-RS specification). Available at
_http://jcp.org/en/jsr/summary?id=370_ .

Common Annotations for the Java Platform 1.3.
Available at _http://jcp.org/en/jsr/detail?id=250_ .

Debugging Support for Other Languages 1.0.
Available at _http://jcp.org/en/jsr/detail?id=45_ .

Standard Tag Library for JavaServer Pages 1.2
(JSTL specification). Available at _http://jcp.org/en/jsr/detail?id=52_
.

JavaServer Faces 2.3 (JSF specification).
Available at _http://jcp.org/en/jsr/detail?id=372_ .

Java Persistence 2.2 (Java Persistence
specification). Available at _http://jcp.org/en/jsr/detail?id=338_ .

Bean Validation 2.0 (Bean Validation
specification). Available at _http://jcp.org/en/jsr/detail?id=380_ .

Managed Beans 1.0 (Managed Beans
specification). Available at _http://jcp.org/en/jsr/detail?id=316_ .

Interceptors 1.2 rev A (Interceptors
specification). Available at _http://jcp.org/en/jsr/detail?id=318_ .

Contexts and Dependency Injection for the Java
EE Platform 2.0 (CDI specification). Available at
_http://jcp.org/en/jsr/detail?id=365_ .

Dependency Injection for Java 1.0 (DI
specification). Available at _http://jcp.org/en/jsr/detail?id=330_ .

 _Java API for WebSocket 1.1_ (WebSocket
specification). Available at _http://jcp.org/en/jsr/detail?id=356_ .

 _Java API for JSON Processing 1.1_ (JSON-P
specification). Available at _http://jcp.org/en/jsr/detail?id=374_ .

 _Java API for JSON Binding 1.0_ (JSON-B
specification). Available at _http://jcp.org/en/jsr/detail?id=367_ .

Java™ EE Security API 1.0. Available at
_http://jcp.org/en/jsr/detail?id=375_ .

Java™ Authentication Service Provider Interface
for Containers 1.1 (JASPIC specification). Available at
_http://jcp.org/en/jsr/detail?id=196_ .
