== Related Documents

This specification refers to the following
documents. The terms used to refer to the documents in this
specification are included in parentheses.

Jakarta™ EE Platform Specification Version 8. Available at: <link needed>.

Java™ Platform, Standard Edition, v8 API Specification (Java SE specification). Available at: http://docs.oracle.com/javase/8/docs/.

Jakarta™ Enterprise Beans Specification, Version 3.2. Available at: <link needed>.

Jakarta™ Server Pages Specification, Version 2.3. Available at: <link needed>.

Jakarta™ Expression Language Specification, Version 3.0. Available at: <link needed>.

Jakarta™ Servlet Specification, Version 4.0. Available at: <link needed>.

Jakarta™ Transaction API Specification, Version 1.2. Available at: <link needed>.

Jakarta™ RESTful Web Services Specification, Version 2.1. Available at: <link needed>.

Jakarta™ Annotations Specification, Version 1.3. Available at: <link needed>.

Jakarta™ Debugging Support for Other Languages Specification, Version 1.0. Available at: <link needed>.

Jakarta™ Standard Tag Library Specification, Version 1.2. Available at: <link needed>.

Jakarta™ Server Faces Specification, Version 2.3. Available at: <link needed>.

Jakarta™ Persistence Specification, Version 2.2. Available at: <link needed>.

Jakarta™ Bean Validation Specification, Version 2.0. Available at: <link needed>.

Jakarta™ Managed Beans Specification, Version 1.0. Available at: <link needed>.

Jakarta™ Interceptors Specification, Version 1.2. Available at: <link needed>.

Jakarta™ Contexts and Dependency Injection Specification, Version 2.0. Available at: <link needed>.

Dependency Injection for Java 1.0 (DI specification). Available at http://jcp.org/en/jsr/detail?id=330

Jakarta™ WebSocket Specification, Version 1.1. Available at: <link needed>.

Jakarta™ JSON Processing Specification, Version 1.1. Available at: <link needed>.

Jakarta™ JSON Binding Specification, Version 1.0. Available at: <link needed>.

Jakarta™ Security Specification, Version 1.0. Available at: <link needed>.

Jakarta™ Authentication Specification, Version 1.1. Available at: <link needed>.
