== Web Profile Definition

This chapter defines the contents of the
Jakarta™ EE 12 Web Profile.

[[a43]]
=== Required Components

The following technologies are required components of the Web Profile:

* Jakarta Annotations 3.0
* Jakarta Authentication 3.1
* Jakarta Authorization 2.0**
* Jakarta Concurrency 3.2*
* Jakarta Contexts and Dependency Injection 5.0*
* Jakarta Data 1.1*
* Jakarta Debugging Support for Other Languages 2.0
* Jakarta Dependency Injection 2.0
* Jakarta Enterprise Beans 4.0 Lite
* Jakarta Expression Language 6.1*
* Jakarta Faces 5.0*
* Jakarta Interceptors 2.2
* Jakarta JSON Binding 3.1*
* Jakarta JSON Processing 2.2*
* Jakarta Pages 4.1*
* Jakarta Persistence 4.0*
* Jakarta Query 1.0**
* Jakarta RESTful Web Services 5.0*
* Jakarta Security 5.0*
* Jakarta Servlet 6.2*
* Jakarta Standard Tag Library 3.1*
* Jakarta Transactions 2.1*
* Jakarta Validation 4.0*
* Jakarta WebSocket 2.3*

*Note:* technologies with an asterisk after them represent updated versions.
*Note:* technologies with a double asterisk after them represent additions to the Web Profile

=== Optional Components

There are no optional components in the Web
Profile.

Web Profile products may support some of the
technologies present in the Jakarta EE Platform and not already listed
in <<a43, Required Components>>,
consistently with their compatibility requirements.

[[a69]]
=== Additional Requirements

Web Profile products must support the
deployment of Jakarta EE web application modules ( _.war_ files). No other
modules types are required to be supported.

The following functionality is required to be supported in Web Profile products:

* Resource annotations defined by the Annotations specification ( _Resource_, _Resources_ )
* JNDI “java:” naming context as described in the JNDI section of the Platform specification
* Jakarta Transactions
