== Web Profile Definition

This chapter defines the contents of the
Jakarta™ EE 9.1 Web Profile.

[[a43]]
=== Required Components

The following technologies are required
components of the Web Profile:

* Jakarta Annotations  2.1*
* Jakarta Authentication 3.0*
* Jakarta Bean Validation 3.0
* Jakarta Concurrency 3.0*
* Jakarta Contexts and Dependency Injection 4.0*
* Jakarta Debugging Support for Other Languages 2.0
* Jakarta Dependency Injection  2.0
* Jakarta Enterprise Beans 4.0 Lite
* Jakarta Expression Language  5.0*
* Jakarta Interceptors 2.1*
* Jakarta JSON Processing 2.1*
* Jakarta JSON Binding 3.0*
* Jakarta Persistence  3.1*
* Jakarta RESTful Web Services 3.1*
* Jakarta Security  3.0*
* Jakarta Standard Tag Library 3.0*
* Jakarta Servlet 6.0*
* Jakarta Server Pages 3.1*
* Jakarta Server Faces 4.0*
* Jakarta Transactions 2.0
* Jakarta WebSocket 2.1*

*Note:* technologies with an asterik after them represent updated versions.

=== Optional Components

There are no optional components in the Web
Profile.

Web Profile products may support some of the
technologies present in the full Jakarta EE Platform and not already listed
in <<a43, Required Components>>,
consistently with their compatibility requirements.

[[a69]]
=== Additional Requirements

Web Profile products must support the
deployment of Jakarta EE web application modules ( _.war_ files). No other
modules types are required to be supported.

The following functionality is required to be supported in Web Profile products:

* Resource annotations defined by the Common Annotations specification ( _Resource_, _Resources_ )
* JNDI “java:” naming context as described in the JNDI section of the Platform specification
* Jakarta Transactions