== Web Profile Definition

This chapter defines the contents of the
Jakarta™ EE 9.1 Web Profile.

[[a43]]
=== Required Components

The following technologies are required
components of the Web Profile:

* Jakarta Servlet 5.0
* Jakarta Server Pages 3.0
* Jakarta Expression Language  4.0
* Jakarta Debugging Support for Other Languages 2.0
* Jakarta Standard Tag Library  2.0
* Jakarta Server Faces  3.0
* Jakarta RESTful Web Services 3.0
* Jakarta WebSocket  2.0
* Jakarta JSON Processing  2.0
* Jakarta JSON Binding  2.0
* Jakarta Annotations  2.0
* Jakarta Enterprise Beans  4.0 Lite
* Jakarta Transactions 2.0
* Jakarta Persistence  3.0
* Jakarta Bean Validation 3.0
* Jakarta Managed Beans 2.0
* Jakarta Interceptors 2.0
* Jakarta Contexts and Dependency Injection  3.0
* Jakarta Dependency Injection  2.0
* Jakarta Security  2.0
* Jakarta Authentication 2.0

=== Optional Components

There are no optional components in the Web
Profile.

Web Profile products may support some of the
technologies present in the full Jakarta EE Platform and not already listed
in <<a43, Required Components>>,
consistently with their compatibility requirements.

[[a69]]
=== Additional Requirements

Web Profile products must support the
deployment of Jakarta EE web application modules ( _.war_ files). No other
modules types are required to be supported.

The following functionality is required to be supported in Web Profile products:

* JNDI “java:” naming context as described in the JNDI section of the Platform specification
* Jakarta Transactions