== Web Profile Definition

This chapter defines the contents of the
Jakarta EE™ 8 Web Profile.

=== [[a43]]Required Components

The following technologies are required
components of the Web Profile:

* Jakarta Servlet 4.0

* Jakarta Server Pages 2.3
* Jakarta Expression Language  3.0
* Jakarta Debugging Support for Other Languages 1.0
* Jakarta Standard Tag Library  1.2
* Jakarta Server Faces  2.3
* Jakarta RESTful Web Services 2.1
* Jakarta WebSocket  1.1
* Jakarta JSON Processing  1.1
* Jakarta JSON Binding  1.0
* Jakarta Annotations  1.3
* Jakarta Enterprise Beans  3.2 Lite
* Jakarta Transactions 1.2
* Jakarta Persistence  2.2
* Jakarta Bean Validation 2.0
* Jakarta Managed Beans 1.0
* Jakarta Interceptors 1.2
* Jakarta Contexts and Dependency Injection  2.0
* Jakarta Dependency Injection  1.0
* Jakarta Security  1.0
* Jakarta Authentication 1.1

=== Optional Components

There are no optional components in the Web
Profile.

Web Profile products may support some of the
technologies present in the full Jakarta EE Platform and not already listed
in link:WebProfile.html#a43[See Required Components]”,
consistently with their compatibility requirements.

=== [[a69]]Additional Requirements

Web Profile products must support the
deployment of Jakarta EE web application modules ( _.war_ files). No other
modules types are required to be supported.
