== Managed Beans Definition

This chapter defines the Managed Beans
component model.

The presentation is organized in two sections.
The first one describes the basic component model for Managed Beans.
This is the minimal set of requirements for Managed Beans
implementations. The second section describes how specifications that
build on this one may extend the basic model to support more advanced
functionality.

For example, in the basic component model,
Managed Beans must provide a no-argument constructor, but a
specification that builds on Managed Beans, such as CDI (JSR-299), can
relax that requirement and allow Managed Beans to provide constructors
with more complex signatures, as long as they follow some well-defined
rules. Similarly, in the basic model, a Managed Bean component must be
declared using the _ManagedBean_ annotation, but other specifications
are allowed to alter this requirement, e.g. to provide a purely
XML-based way to turn a class into a Managed Bean.

=== Basic Model

[[a24]]
==== Component Definition

A Managed Bean can be declared by annotating
its class with the _jakarta.annotation.ManagedBean_ annotation.

A Managed Bean must not be: a final class, an
abstract class, a non-static inner class.

A Managed Bean may not be serializable, unlike
a regular JavaBean component.

Managed Bean implementations must support
Managed Beans that have a no-argument constructor.

[[a29]]
==== Naming

A Managed Bean may optionally have a name, a
_String_ .

The name can be specified using an element of
the _ManagedBean_ annotation.

[source, java]
----
 @ManagedBean(“cart“)
 public class ShoppingCart \{ ... }
----

Managed Bean names must be unique within a Jakarta
EE module. It is an error if a Jakarta EE module contains a Jakarta Enterprise Bean component
and a Managed Bean with the same name.

For each named Managed Bean, Jakarta EE containers
must make available the following entries in JNDI, using the same naming
scheme used for Jakarta Enterprise Bean components.

In the application namespace:
----
 java:app/<module-name>/<bean-name>
----

In the module namespace of the module
containing the Managed Bean:
----
 java:module/<bean-name>
----

Jakarta EE applications may obtain a new instance
of a Managed Bean by looking up the corresponding names in JNDI or by
using resource injection. See Chapter 5 of the Jakarta EE Platform
specification for more details.


[[a47]]
==== Lifecycle and Resource Injection

Managed Beans may use the
_jakarta.annotation.PostConstruct_ and _jakarta.annotation.PreDestroy_
annotations to identify methods to be called back by the container at
the appropriate points in the bean’s lifecycle.

In a Jakarta EE implementation, a Managed Bean may
use any of the resource injection functionality laid out in Chapter 5
of the Jakarta EE Platform specification, “Resources, Naming and
Injection“. A Managed Bean does not have its own component-scoped
_“java:comp”_ namespace. For this reason, Managed Beans should define
resources in the _“java:module”_ namespace or above. JNDI lookup
operations from a method defined on a Managed Bean will use the naming
context of that method’s caller.

[[a50]]
==== Threading

Method invocations on a Managed Bean execute in
the same thread as the caller.

==== Interceptors

A Managed Bean may use interceptors as defined
in the Interceptor specification.

=== Extensions

Specifications that build on the present one
(called here an “extension specification”) may modify some of the
aspects of the basic model, as detailed in the rest of this section.

==== Component Definition

An extension specification may provide ways to
declare a Managed Bean that go beyond those in the Basic Model
<<a24, Component Definition>>.

An extension specification may allow a Managed
Bean to declare constructors with complex signatures, thus dropping the
requirement that a no-argument constructor be present.

==== Naming

An extension specification may offer
alternative ways to name a Managed Bean, e.g. as a side-effect of
placing some other annotation on the bean class, but, if specified, the
_ManagedBean(”...”)_ annotation takes priority, and with it the rules in
the Basic Model <<a29, Naming>>.

Of course an extension specification may also
introduce one or more additional namespaces in which some or all Managed
Beans get registered, either with the Managed Bean name defined in the
Basic Model <<a29, Naming>> or with an
independently defined name.

==== Lifecycle and Resource Injection

An extension specification may define its own
lifecycle model, adding e.g. pooling, sharing of instances, etc., beyond
the basic model described in the Basic Model <<a47, Lifecycle and Resource Injection>>.

An extension specification may allow Managed
Beans to have their own _“java:comp”_ namespace.

==== Threading

An extension specification may add its own
threading requirements, overriding any requirements set in
the Basic Model <<a50, Threading>>.

For example, invocations on a [proxy for] a
Managed Bean may be performed using a different thread than the
caller’s.

==== Interceptors

An extension specification may add its own
interceptor-like facilities to the predefined one.

For example, an extension specification may
allow declaring type-safe interceptors, defined using a different set of
APIs than those in the _jakarta.interceptor_ package.
