== Compatibility and Migration

This chapter summarizes compatibility and
migration issues for the Jakarta(TM) EE platform. The specifications for each
of the component technologies included in Jakarta EE also describe
compatibility and migration issues for that technology in much more
detail.

===  Compatibility

The word compatibility covers many different
concepts. Jakarta EE products are compatible with the Jakarta EE specification
if they implement the APIs and behavior required by the specification.
Applications are compatible with a release of the Jakarta EE platform if
they only depend on APIs and behavior defined by that release of the
platform. A new release of the Jakarta EE platform is compatible with
previous releases of the platform if all portable applications written
to the previous release of the platform will also run unchanged and with
identical behavior on the new release of the platform.

Compatibility is a core value of the Jakarta EE
platform. A Jakarta EE product is required to support portable applications
written to previous versions of the platform. Compatibility and
portability work together to provide the Write Once, Run Anywhere value
of the Jakarta EE platform. Jakarta EE products conform to the Jakarta EE
specifications by providing APIs and behavior as required by the
specifications. Portable applications depend only on the APIs and
behavior required by the Jakarta EE specifications. In general, portable
applications written to a previous version of the platform will continue
to work without change and with identical behavior on the current
version of the platform.

[[a3901]]
==== Backwards Compatibility for Jakarta EE 11

===== Removed Technologies
* Jakarta Managed Beans
* Jakarta SOAP with Attachments
* Jakarta XML Binding
* Jakarta XML Web Services

Support for Jakarta Managed Beans was deprecated previously and is now removed from Jakarta EE 11 platform.  The
jakarta.annotation.ManagedBean annotation is no longer provided with the Jakarta Annotations 3.0 release.  Applications using the 
ManagedBean annotation should transition to another bean defining annotation such as jakarta.inject.Inject

Support for Jakarta XML Web Services, along with the Jakarta XML Binding and the SOAP with attachments
specifications, was made optional with the Jakarta EE 10 release, and is now removed
from the Jakarta EE 11 platform.  Jakarta EE products can continue to support these technologies
to work with the Jakarta EE 11 platform just like other stand-alone specifications that are not part of the platform.

==== Backwards Compatibility for Jakarta EE 10

===== Removed Technologies
* Entity Beans, both Container and Bean Managed Persistence (Jakarta Enterprise Beans 4.0, Optional Features, Chapters 3 - 7)
* Embeddable EJB Container (Jakarta Enterprise Beans, Core Features 4.0, Chapter 17)

==== Backwards Compatibility for Jakarta EE 9
Due to the migration from the `javax` namespace to the `jakarta` namespace, Jakarta
EE 9 is not source-code compatible or binary compatible with previous releases.
However, Jakarta EE 9 is behavior compatible with all `jakarta` APIs present
sharing identical method signatures and behavior with their `javax` equivalents.

Applications migrating to Jakarta EE 9 from previous releases will require
modification in the areas detailed in the sections below.

===== `javax` to `jakarta` Namespace
The main requirement for Jakarta EE 9 was to change the `javax` namespace to the `jakarta` namespace.
This requirement demanded changes across all of the Specification documents, the APIs, the Javadocs, the TCKs (Technology Compatibility Kits), and the CIs (Compatible Implementations).
In turn, this required change will also affect applications.
For example, all `import` statements will need to be updated to reflect the updated `jakarta` package names.

====== Properties
Java(TM) properties are often used to configure the features of Jakarta EE.
In the past, many of these properties were prefaced with `javax`.
But now, along with the package name update, these property names will be prefaced with `jakarta`.
It is implementation-specific whether the old `javax` property names will be honored in Jakarta EE 9 compatible implementations.

====== Schemas
Schemas (or XSDs or DTDs) are used by some of the Jakarta EE features to define the content and format of their respective XML files.
Previous versions of the schemas referenced the http://xmlns.jcp.org/xml/ns/javaee/ and http://java.sun.com/xml/ns/javaee/ namespaces.
Following the `jakarta` namespace update requirement, Jakarta EE 9 also requires the schema namespace to be updated to `https://jakarta.ee/xml/ns/jakartaee`.
Accordingly, application deployment descriptors will need to be updated to reference these updated namespaces.
The complete list of updated schemas for Jakarta EE 9 can be found here: https://jakarta.ee/xml/ns/jakartaee/#9

NOTE: Jakarta EE 9 only requires past schema support to (Java EE(TM)) Jakarta EE 8.
Support for schemas prior to Java EE 8 is not required.

===== Removed Technologies
The following technologies have been removed from Jakarta EE 9 to lower the bar of entry for new compatible implementations.
In most cases, this action removes the full Specification.
While in other cases, only a portion (chapter) of a Specification is removed.
For Jakarta EE 9, the following technologies were removed from the Platform: 

* Jakarta XML Registries
* Jakarta XML RPC
* Jakarta Deployment
* Jakarta Management
* Support for Distributed Interoperability in the EJB 3.2 Core Specification, Chapter 10

Existing Compatible Implementations may decide to continue to support these removed technologies, but there are no TCK tests in Jakarta EE 9 to verify compatibility.
There is no requirement for new Compatible Implementations to support these removed technologies.

===== Migration Tools
Compatible Implementations, IDEs, and other tools are providing mechanisms to make these changes as painless as possible.
One such effort is the Eclipse Transformer Project (https://projects.eclipse.org/projects/technology.transformer).
This framework aids with the binary transformation of Java(TM) class files -- replacing the `javax.*` package references to the corresponding `jakarta.*` packages.
In addition to being used with several of the Jakarta EE 9 Compatible Implementations, the Transformer has also been used to transform test buckets and other utility libraries.

=== Migration

Migration is the act of converting an
application to use new facilities introduced in this release of the
platform.
Given the required move from the `javax` namespace to the `jakarta` namespace in
Jakarta EE 9 and the removal of some technologies, some migration of applications may be required.
Some application servers may provide additional facilities to make this migration 
more consumable.
Still, an application will be better positioned for the future 
by converting it to use the defined features of the Jakarta EE platform.
Reference <<a3901, "Backwards Compatibility">> for more information.

Also, an application may be improved (better performance, simpler to develop, more flexible, etc.) by converting it to use newer facilities of the Jakarta EE platform as outlined in the next subsections.

==== Jakarta Persistence

Jakarta Persistence provides a much richer set of
modeling capabilities and object/relational mapping capabilities than
EJB CMP entity beans and is significantly easier to use.

Support for EJB CMP and BMP entity beans has
been optional since the Java EE 7 release. Support for EJB CMP 1.1
entity beans has been optional since Java EE 5. Applications are
strongly encouraged to migrate applications using entity beans to
Jakarta Persistence.

==== Jakarta XML Web Services

Jakarta XML Web Services, along with the Jakarta XML Binding and the SOAP with
attachments specifications, provides simpler and more complete support
for web services than is available using the older JAX-RPC technology. Support
for JAX-RPC was made optional with the Java EE 7 release, and was removed
from the Jakarta EE 9 platform.
Applications that provide web services using JAX-RPC should consider
migrating to the Jakarta XML Web Services API. Note that because both technologies support
the same web service interoperability standards, clients and services
can be migrated to the new API independently.

Jakarta XML and SOAP technologies have been removed from the Jakarta EE Platform with
the Jakarta EE 11 release.  Application using XML and SOAP technologies should consider
using the RESTful Web Services API for their web services.