== Compatibility and Migration

This chapter summarizes compatibility and
migration issues for the Jakarta(TM) EE platform. The specifications for each
of the component technologies included in Jakarta EE also describe
compatibility and migration issues for that technology in much more
detail.

===  Compatibility

The word compatibility covers many different
concepts. Jakarta EE products are compatible with the Jakarta EE specification
if they implement the APIs and behavior required by the specification.
Applications are compatible with a release of the Jakarta EE platform if
they only depend on APIs and behavior defined by that release of the
platform. A new release of the Jakarta EE platform is compatible with
previous releases of the platform if all portable applications written
to the previous release of the platform will also run unchanged and with
identical behavior on the new release of the platform.

Compatibility is a core value of the Jakarta EE
platform. A Jakarta EE product is required to support portable applications
written to previous versions of the platform. Compatibility and
portability work together to provide the Write Once, Run Anywhere value
of the Jakarta EE platform. Jakarta EE products conform to the Jakarta EE
specifications by providing APIs and behavior as required by the
specifications. Portable applications depend only on the APIs and
behavior required by the Jakarta EE specifications. In general, portable
applications written to a previous version of the platform will continue
to work without change and with identical behavior on the current
version of the platform.

[[a3901]]
==== Backwards Compatibility for Jakarta EE 9

The Backwards Compatibility Requirements for Jakarta EE Specifications is documented here: 
_https://eclipse-ee4j.github.io/jakartaee-platform/CompatibilityRequirements_.
Unfortunately, some of these requirements were not able to be adhered to for Jakarta EE 9.
This was due to the required namespace change from `javax` to `jakarta`.

===== `javax` to `jakarta` Namespace Change
Per the Jakarta EE 9 Release Plan (https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9ReleasePlan), the whole `javax` namespace needed to change to `jakarta`.
This had a ripple effect across all of the Specification documents, the APIs, the Javadocs, the TCKs (Technology Compatibility Kits), and the CIs (Compatible Implementations).
In turn, this required change will also affect applications.
Thus, the requirement that changes _"must be source-code compatible, binary compatible, and behavior compatible for applications"_ can not be honored for Jakarta EE 9.

Compatible Implementations, IDEs, and other tools are providing mechanisms to make this change as painless as possible.
One such effort is the Eclipse Transformer Project (https://projects.eclipse.org/projects/technology.transformer).
This framework aids with the binary transformation of Java(TM) class files -- replacing the `javax.*` package references to the corresponding `jakarta.*` packages.
In addition to being used with several of the Jakarta EE 9 Compatible Implementations, the Transformer has also been used to transform test buckets and other utility libraries.

====== Schemas
blah, blah, blah

====== Properties
blah, blah, blah

===== Removed Technologies
blah, blah, blah

=== Migration

Migration is the act of converting an
application to use new facilities introduced in this release of the
platform.
Given the required move from the `javax` namespace to the `jakarta` namespace in
Jakarta EE 9, some migration of applications may be required.
Some application servers may provide additional facilities to make this migration 
more consumable.
Still, an application may be better positioned for the future 
by converting it to use the new `jakarta` namespace of the
Jakarta EE platform.
Reference <<a3901, "Backwards Compatibility">> for more information.

Also, an application may be improved (better performance, simpler to develop, more flexible, etc.) by converting it to use newer facilities of the Jakarta EE platform as outlined in the next subsections.

==== Jakarta Persistence

Jakarta Persistence provides a much richer set of
modeling capabilities and object/relational mapping capabilities than
EJB CMP entity beans and is significantly easier to use.

Support for EJB CMP and BMP entity beans has
been made optional with the Java EE 7 release. Support for EJB CMP 1.1
entity beans has been optional since Java EE 5. Applications are
strongly encouraged to migrate applications using EJB entity beans to
Jakarta Persistence.

==== Jakarta XML Web Services (optional)

Jakarta XML Web Services, along with the Jakarta XML Binding and the Metadata for
Web Services specifications, provides simpler and more complete support
for web services than is available using the older JAX-RPC technology. Support
for JAX-RPC was made optional with the Java EE 7 release, and is now removed
from the Jakarta EE 9 platform.
Applications that provide web services using JAX-RPC should consider
migrating to the Jakarta XML Web Services API. Note that because both technologies support
the same web service interoperability standards, clients and services
can be migrated to the new API independently.
