[[a3439]]
== Future Directions

This version of the Jakarta™ EE Platform specification includes most of the
facilities needed by enterprise applications. Still, there is always
more to be done. This chapter briefly describes our plans for future
versions of this specification. Please keep in mind that all of this is
subject to change. Your feedback is encouraged.

The following sections describe additional
facilities we would like to include in future versions of this
specification. Many of the APIs included in the Jakarta EE platform will
continue to evolve on their own and we will include the latest version
of each API.

=== Jakarta EE SPI

Many of the APIs that make up the Jakarta EE
platform include an SPI layer that allows service providers or other
system level components to be plugged in. This specification does not
describe the execution environment for all such service providers, nor
the packaging and deployment requirements for all service providers.
However, the Jakarta Connectors Specification does define the requirements
for certain types of service providers called resource adapters, and the
Jakarta Authorization specification defines requirements for
security service providers. Future versions of this specification will
more fully define the Jakarta EE SPI.

=== SecurityManager Deprecation

With the https://openjdk.java.net/jeps/411[JEP 411: Deprecate the Security Manager for Removal] initiative that has deprecated several SecurityManager related methods in Java SE 17, and further limited functionality in Java SE 18, it is clear that Jakarta EE needs to remove requirements related to the SecurityManager. Discussions with OpenJDK developers have made it clear that there will be no replacement, and conversations along the lines of maintaining similar integration points at the JDK level have confirmed that the OpenJDK team does not want to support such integration points. This leaves Jakarta EE with the option of either introducing its own specification and requirements around similar functionality, or simply removing any requirements related to the SecurityManager. Given that replacing the SecurityManager permission checks in the JDK would require bytecode enhancement of implementations, it seems unlikely that this would be an achievable effort given the low level nature of the integration, and the general lack of effectiveness of the SecurityManager model as highlighted in the JEP 411 issue.

The decided course of action is to announce that the SecurityManager is being deprecated in Jakarta EE10 for removal in a subsequent release, and that EE10 would be the last release with any requirements relating to the SecurityManager. Further, the rapid pace of Java SE releases brings the possibility that implementers may want to certify on EE10 and earlier releases with a Java SE version that has eliminated the SecurityManager. Existing TCK SecurityManager requirements in EE10 and earlier EE release may have to be relaxed as challenges are filed. The platform team needs to be receptive to relaxing these requirements if the need arises.

=== Java Platform Module System (JPMS)

The EE10 release introduced a requirement for every component specification API jar included a JPMS module-info.class suitable for use with OpenJDK tools like jlink and jdeps. The contents of module-info.class files are not standard, portable, may change without notice and there is no requirement around testing of JPMS in API jar signature tests or TCKs. Vendors are free to create their own API jars that pass the signature tests, but include no JPMS module-info.class files or JPMS module-info.class files with different or conflicting contents. It is a future task to determine whether EE containers should support deployments that make use of JPMS information.
