[[a2845]]
== Interoperability

This chapter describes the interoperability
features for the Jakarta™ EE Platform.

=== Introduction to Interoperability

The Jakarta EE platform will be used by enterprise
environments that support clients of many different types. The
enterprise environments will add new services to existing Enterprise
Information Systems (EISs). They will be using various hardware
platforms and applications written in various languages.

In particular, the Jakarta EE platform may be used
in enterprise environments to bring together any of the following kinds
of applications:

* applications written in such languages as C++
and Visual Basic.
* applications running on a personal computer
platform, or Unix® workstation.
* standalone Java™ technology-based applications
that are not directly supported by the Jakarta EE platform.

It is the interoperability features of the
Jakarta EE platform, set out in this chapter, that make it possible for it
to provide indirect support for various types of clients, different
hardware platforms, and a multitude of software applications. The
interoperability features of the Jakarta EE platform permit the underlying
disparate systems to work together seamlessly, while hiding much of the
complexity required to join these pieces together.

The interoperability features for the
current Jakarta EE platform release may allow:

* Jakarta EE applications to connect to legacy
systems using CORBA or low-level socket interfaces.
* Jakarta EE applications to connect to other
Jakarta EE applications across multiple Jakarta EE products and platforms.

In this version of the specification,
interoperability between Jakarta EE applications running in different
platforms may be accomplished through the HTTP protocol, possibly using SSL,
or the OMG (CORBA) protocol.

=== Interoperability Protocols

This specification allows a Jakarta EE
product to support a standard set of protocols and formats to ensure
interoperability between Jakarta EE applications and with other
applications that also implement these protocols and formats. The
specification supports the following groups of protocols and
formats:

* Internet and web protocols
* OMG protocols (optional)
* Java technology protocols
* Data formats

Most of these protocols and formats are
supported by Java SE and by the underlying operating system.

[[a2865]]
==== Internet and Web Protocols

Standards based Internet protocols are the means
by which different pieces of the platform communicate. The Jakarta EE
platform typically supports the following Internet protocols, as
described in the corresponding technology specifications:

* TCP/IP protocol family—This is the core
component of Internet communication. TCP/IP and UDP/IP are the standard
transport protocols for the Internet. TCP/IP is supported by Java SE and
the underlying operating system.
* HTTP 1.1—This is the core protocol of web
communication. As with TCP/IP, HTTP 1.1 is supported by Java SE and the
underlying operating system. A Jakarta EE web container must be capable of
advertising its HTTP services on the standard HTTP port, port 80.
* HTTP/2—Server-side support for the HTTP/2
protocol is required by the Servlet specification.
* SSL 3.0, TLS 1.2—SSL 3.0 (Secure Socket Layer)
represents the security layer for Web communication. It is available
indirectly when using the _https_ URL as opposed to the _http_ URL. A
Jakarta EE web container must be capable of advertising its HTTPS service
on the standard HTTPS port, port 443. 
* SOAP 1.1—SOAP is a presentation layer
protocol for the exchange of XML messages. Support for SOAP layered on
HTTP is optional, as described in the Jakarta XML-based RPCfootnote:removed9[Removed in Jakarta EE 9] and 
Jakarta XML Web Servicesfootnote:optional9[Made optional in Jakarta EE 9] specifications.
* SOAP 1.2—SOAP 1.2 is the version of the SOAP
protocol standardized through W3C and supported by Jakarta XML Web Servicesfootnote:optional9[].
* WS-I Basic Profile 1.1—The WS-I Basic
Profile, in combination with the Simple SOAP Binding Profile and
Attachment Profile, describes interoperability requirements for the use
of SOAP 1.1, WSDL 1.1, and MIME-based SOAP with Attachments. It is
optional as defined by the Jakarta XML-based RPCfootnote:removed9[] and 
Jakarta XML Web Servicesfootnote:optional9[] specifications.
* WebSocket protocol—The WebSocket protocol
enables two-way communication layered over TCP. It enables
bi-directional communication over a single connection established by an
initial HTTP handshake and upgrade request. The WebSocket protocol has
been standardized by IETF under RFC 6455.

[[a2875]]
==== OMG Protocols (optional)

Support for the Object Management Group (OMG) based protocols is optional for Jakarta EE 9.

==== Java Technology Protocols

This specification requires the Jakarta EE platform
to support the JRMP protocol, which is the Java technology-specific
Remote Method Invocation (RMI) protocol. JRMP is a required component of
Java SE.

JRMP is a distributed object model for the Java
programming language. Distributed systems, running in different address
spaces and often on different hosts, must be able to communicate with
each other. JRMP permits program-level objects in different address
spaces to invoke remote objects using the semantics of the Java
programming language object model.

Complete information on the JRMP specification
can be found at
_http://docs.oracle.com/javase/8/docs/technotes/guides/rmi_ .

[[a2884]]
==== Data Formats

In addition to the protocols that allow
communication between components, this specification requires Jakarta EE
platform support for a number of data formats. These formats provide the
definition for data exchanged between components.

The following data formats must be supported:

* XML 1.0—The XML format can be used to
construct documents, RPC messages, etc. The JAXP API provides support
for processing XML format data. The Jakarta XML-based RPCfootnote:removed9[] API provides support for XML
RPC messages, as well as a mapping between Java classes and XML.
* JSON—JSON is a language-neutral plain text
format commonly used to transfer structured data between a server and
web application. The Jakarta JSON Processing API provides support for the parsing,
generation, transformation, and querying of JSON text. The Jakarta JSON Binding API
provides support for mapping between JSON text and Java objects.
* HTML 4.01—This represents the minimum web
browser standard document format. While all Jakarta EE APIs with the
exception of Jakarta Server Faces are agnostic to the version of the browser document
format, Jakarta EE web clients must be able to display HTML 4.01 documents.
* Image file formats—The Jakarta EE platform must
support GIF, JPEG, and PNG images. Support for these formats is provided
by the _java.awt.image_ APIs (see the URL:
_http://docs.oracle.com/javase/8/docs/api/java/awt/image/package-summary.html_
) and by Jakarta EE web clients.
* JAR files—JAR (Java Archive) files are the
standard packaging format for Java technology-based application
components, including the ejb-jar specialized format, the Web
application archive (WAR) format, the Resource Adapter archive (RAR),
and the Jakarta EE enterprise application archive (EAR) format. JAR is a
platform-independent file format that permits many files to be
aggregated into one file. This allows multiple Java components to be
bundled into one JAR file and downloaded to a browser in a single HTTP
transaction. JAR file formats are supported by the _java.util.jar_ and
_java.util.zip_ packages. For complete information on the JAR
specification, see
_http://docs.oracle.com/javase/8/docs/technotes/guides/jar_ .
* Class file format—The class file format is
specified in the Java Virtual Machine specification. Each class file
contains one Java programming language type—either a class or an
interface—and consists of a stream of 8-bit bytes. For complete
information on the class file format, see
_http://docs.oracle.com/javase/specs/_ .
