[appendix]
[[relateddocs]]
== Related Documents

This specification refers to the following
documents. The terms used to refer to the documents in this
specification are included in parentheses.

_Jakarta™ EE Core Profile Specification, Version 11.0_. Available at: _https://jakarta.ee/specifications/coreprofile/11/_

_Jakarta™ EE Web Profile Specification, Version 11.0_. Available at: _https://jakarta.ee/specifications/webprofile/11/_

_Java™ Platform, Standard Edition (Java SE specification), v17_. Available at: _https://www.jcp.org/en/jsr/detail?id=392_

_Java™ Platform, Standard Edition, v17 API Specification_. Available at: _https://docs.oracle.com/javase/17/docs/_

_Jakarta™ Enterprise Beans Specification, Version 4.0_. Available at: _https://jakarta.ee/specifications/enterprise-beans/4.0/_

_Jakarta™ Server Pages Specification, Version 4.0_. Available at: _https://jakarta.ee/specifications/pages/4.0/_

_Jakarta™ Expression Language Specification, Version 6.0_. Available at: _https://jakarta.ee/specifications/expression-language/6.0/_

_Jakarta™ Annotations Specification, Version 3.0_. Available at: _https://jakarta.ee/specifications/annotations/3.0/_

_Jakarta™ Servlet Specification, Version 6.1_. Available at: _https://jakarta.ee/specifications/servlet/6.1/_

_JDBC™ 4.3 API (JDBC specification)_. Available at: _https://jcp.org/en/jsr/detail?id=221_

_Java™ Naming and Directory Interface 1.2 Specification (JNDI specification)_. Available at: _https://docs.oracle.com/javase/8/docs/technotes/guides/jndi/index.html_

_Jakarta™ Messaging Specification, Version 3.1_. Available at: _https://jakarta.ee/specifications/messaging/3.1/_

_Jakarta™ Transaction Specification, Version 2.0_. Available at: _https://jakarta.ee/specifications/transactions/2.0/_

_Jakarta™ Mail Specification, Version 2.1_. Available at: _https://jakarta.ee/specifications/mail/2.1/_

_Jakarta Activation, Version 2.1_. Available at: _https://jakarta.ee/specifications/activation/2.1/_

_Jakarta™ Connectors Specification, Version 2.1_. Available at: _https://jakarta.ee/specifications/connectors/2.1/_

_Jakarta™ XML Web Services Specification, Version 4.0_. Available at: _https://jakarta.ee/specifications/xml-web-services/4.0/_

_Jakarta™ SOAP with Attachments Specification, Version 3.0_. Available at: _https://jakarta.ee/specifications/soap-attachments/3.0/_

_Jakarta™ RESTful Web Services Specification, Version 4.0_. Available at: _https://jakarta.ee/specifications/restful-ws/4.0/_

_Jakarta™ Authorization Specification, Version 3.0_. Available at: _https://jakarta.ee/specifications/authorization/3.0/_

_Jakarta™ Authentication Specification, Version 3.1_. Available at: _https://jakarta.ee/specifications/authentication/3.1/_

_Jakarta™ Security Specification, Version 4.0_. Available at: _https://jakarta.ee/specifications/security/4.0/_

_Jakarta™ Debugging Support for Other Languages Specification, Version 2.0_. Available at: _https://jakarta.ee/specifications/debugging/2.0/_

_Jakarta™ Standard Tag Library Specification, Version 3.0_. Available at: _https://jakarta.ee/specifications/tags/3.0/_

_Jakarta™ Server Faces Specification, Version 4.1_. Available at: _https://jakarta.ee/specifications/faces/4.1/_

_Jakarta™ Persistence Specification, Version 3.2_. Available at: _https://jakarta.ee/specifications/persistence/3.2/_

_Jakarta™ Validation Specification, Version 3.1_. Available at: _https://jakarta.ee/specifications/bean-validation/3.1/_

_Jakarta™ Interceptors Specification, Version 2.2_. Available at: _https://jakarta.ee/specifications/interceptors/2.2/_

[[cdi-spec]]
_Jakarta™ Contexts and Dependency Injection Specification, Version 4.1_. Available at: _https://jakarta.ee/specifications/cdi/4.1/_

_Jakarta™ Dependency Injection Specification, Version 2.0_. Available at: _https://jakarta.ee/specifications/dependency-injection/2.0/_

_Jakarta™ WebSocket Specification, Version 2.2_. Available at: _https://jakarta.ee/specifications/websocket/2.2/_

_Jakarta™ JSON Processing Specification, Version 2.1_. Available at: _https://jakarta.ee/specifications/jsonp/2.1/_

_Jakarta™ JSON Binding Specification, Version 3.0_. Available at: _https://jakarta.ee/specifications/jsonb/3.0/_

_Jakarta™ Concurrency Specification, Version 3.1_. Available at: _https://jakarta.ee/specifications/concurrency/3.1/_

_Jakarta™ Batch Specification, Version 2.1_. Available at: _https://jakarta.ee/specifications/batch/2.1/_

_Jakarta™ Data Specification, Version 1.0_. Available at: _https://jakarta.ee/specifications/data/1.0/_

_Jakarta EE Specification Process (JESP), Version 1.4_. Available at: _https://jakarta.ee/about/jesp/_

Extension Mechanism Architecture, Available at
_https://docs.oracle.com/javase/8/docs/technotes/guides/extensions/index.html_

Optional Package Versioning, Available at
_https://docs.oracle.com/javase/8/docs/technotes/guides/extensions/index.html_

JAR File Specification, Available at
_https://docs.oracle.com/javase/8/docs/technotes/guides/jar/jar.html_

_The Common Object Request Broker: Architecture
and Specification_ (CORBA 2.3.1 specification), Available at
_https://www.omg.org/cgi-bin/doc?formal/99-10-07_

CORBA 2.6 - Chapter 26 - Secure
Interoperability, Available at
_https://www.omg.org/cgi-bin/doc?formal/01-12-30_

_IDL To Java™ Language Mapping Specification_ ,
Available at _https://www.omg.org/cgi-bin/doc?ptc/2000-01-08_

_Java™ Language To IDL Mapping Specification_ ,
Available at _https://www.omg.org/cgi-bin/doc?ptc/2000-01-06_

_Interoperable Naming Service,_ Available at
_https://www.omg.org/cgi-bin/doc?ptc/00-08-07_

_Transaction Service Specification_ (OTS
specification), Available at
_https://www.omg.org/cgi-bin/doc?formal/2001-11-03_

_The SSL Protocol, Version 3.0._ Available at
_https://tools.ietf.org/html/rfc6101_

Architectural Styles and the Design of
Network-based Software Architectures (REST), R. Fielding, Ph.d
dissertation, University of California, Irvine, 2000. Available at
_https://ics.uci.edu/~fielding/pubs/dissertation/top.htm_

Java™ Community Process
_SM_ 2: Process Document, Version 2.10 (March 21, 2016). Available at
_https://jcp.org/en/procedures/jcp2_

// generates a line between text and footnotes for pdf and html generation.
'''
