== Related Documents

This specification refers to the following
documents. The terms used to refer to the documents in this
specification are included in parentheses.

 _Java™ Platform, Enterprise Edition
Specification Version 8_ (this specification). Available at
_http://jcp.org/en/jsr/detail?id=366_ .

 _Java™ Platform, Standard Edition, v8 API
Specification_ (Java SE specification). Available at
_http://docs.oracle.com/javase/8/docs/[]http://docs.oracle.com/javase/8/docs/._

 _Enterprise JavaBeans™ Specification, Version
3.2_ (EJB specification). Available at
_http://jcp.org/en/jsr/detail?id=345_ .

 _JavaServer Pages™ Specification, Version 2.3_
(JSP specification). Available at _http://jcp.org/en/jsr/detail?id=245_
.

 _Expression Language Specification, Version
3.0_ (EL specification). Available at
_http://jcp.org/en/jsr/detail?id=341_ .

 _Common Annotations for the Java Platform
Specification 1.3_ . Available at _http://jcp.org/en/jsr/detail?id=250_
.

 _Java™ Servlet Specification, Version 4.0_
(Servlet specification). Available at
_http://jcp.org/en/jsr/detail?id=369_ .

 _JDBC™ 4.2 API_ (JDBC specification). Available
at _http://jcp.org/en/jsr/detail?id=221_ .

 _Java™ Naming and Directory Interface 1.2
Specification_ (JNDI specification). Available at
_http://docs.oracle.com/javase/8/docs/technotes/guides/jndi/index.html[]http://docs.oracle.com/javase/8/docs/technotes/guides/jndi/index.html._

 _Java™ Message Service, Version 2.0_ (JMS
specification). Available at _http://jcp.org/en/jsr/detail?id=343_ .

 _Java™ Transaction API, Version 1.2_ (JTA
specification). Available at _http://jcp.org/en/jsr/detail?id=907_ .

 _Java™ Transaction Service, Version 1.0_ (JTS
specification). Available at
_http://www.oracle.com/technetwork/java/javaee/jts-spec095-1508547.pdf_
.

 _JavaMail™ API Specification Version 1.6_
(JavaMail specification). Available at
_http://jcp.org/en/jsr/detail?id=919_ .

 _JavaBeans™ Activation Framework Specification
Version 1.1_ (JAF specification). Available at
_http://www.oracle.com/technetwork/java/javase/tech/index-jsp-138795.html_
.

 _Java EE™ Connector Architecture 1.7_
(Connector specification). Available at
_http://jcp.org/en/jsr/detail?id=322_ .

Web Services for Java EE 1.4 (Web Services
specification). Available at _http://jcp.org/en/jsr/detail?id=109_ .

Java™ API for XML-based RPC 1.1 (JAX-RPC
specification). Available at _http://jcp.org/en/jsr/detail?id=101_ .

SOAP with Attachments API for Java™ 1.3 (SAAJ
specification). Available at
_http://download.oracle.com/otndocs/jcp/jaxm-1.3-mrel-spec-oth-JSpec/_ .

Java™ API for XML Registries 1.0 (JAXR
specification). Available at _http://jcp.org/en/jsr/detail?id=93_ .

 _JAX-RS: The JavaTM API for RESTful Web
Services 2.1_ (JAX-RS specification). Available at
_http://jcp.org/en/jsr/summary?id=370_ .

Java™ Platform, Enterprise Edition Management
Specification 1.1 (Java EE Management specification). Available at
_http://jcp.org/en/jsr/detail?id=77_ .

Java™ Platform, Enterprise Edition Deployment
Specification 1.2 (Java EE Deployment specification). Available at
_http://jcp.org/en/jsr/detail?id=88_ .

Java™ Authorization Service Provider Contract
for Containers 1.5 (JACC specification). Available at
_http://jcp.org/en/jsr/detail?id=115_ .

Java™ Authentication Service Provider Interface
for Containers 1.1 (JASPIC specification). Available at
_http://jcp.org/en/jsr/detail?id=196_ .

Java™ EE Security API 1.0. Available at
_http://jcp.org/en/jsr/detail?id=375_ .

Debugging Support for Other Languages 1.0.
Available at _http://jcp.org/en/jsr/detail?id=45_ .

Standard Tag Library for JavaServer Pages 1.2
(JSTL specification). Available at _http://jcp.org/en/jsr/detail?id=52_
.

Web Services Metadata for the Java Platform
2.1. Available at _http://jcp.org/en/jsr/detail?id=181_ .

JavaServer Faces 2.3 (JSF specification).
Available at _http://jcp.org/en/jsr/detail?id=372_ .

Java Persistence 2.2 (Java Persistence
specification). Available at _http://jcp.org/en/jsr/detail?id=338_ .

Bean Validation 2.0 (Bean Validation
specification). Available at _http://jcp.org/en/jsr/detail?id=380_ .

Managed Beans 1.0 (Managed Beans
specification). Available at _http://jcp.org/en/jsr/detail?id=316_ .

Interceptors 1.2 _rev A_ (Interceptors
specification). Available at _http://jcp.org/en/jsr/detail?id=318_ .

Contexts and Dependency Injection for the Java
EE Platform 2.0 (CDI specification). Available at
_http://jcp.org/en/jsr/detail?id=365_ .

Dependency Injection for Java 1.0 (DI
specification). Available at _http://jcp.org/en/jsr/detail?id=330_ .

 _Java API for WebSocket 1.1_ (WebSocket
specification). Available at _http://jcp.org/en/jsr/detail?id=356_ .

 _Java API for JSON Processing 1.1_ (JSON-P
specification). Available at _http://jcp.org/en/jsr/detail?id=374_ .

 _Java API for JSON Binding 1.0_ (JSON-B
specification). Available at _http://jcp.org/en/jsr/detail?id=367_ .

 _Concurrency Utilities for Java EE 1.0_
(Concurrency Utilities specification). Available at
_http://jcp.org/en/jsr/detail?id=236_ .

 _Batch Applications for the Java Platform 1.0
rev A_ (Batch specification). Available at
_http://jcp.org/en/jsr/detail?id=352_ .

Extension Mechanism Architecture, Available at
_http://docs.oracle.com/javase/8/docs/technotes/guides/extensions/index.html_
.

Optional Package Versioning, Available at
_http://docs.oracle.com/javase/8/docs/technotes/guides/extensions/index.html_
.

JAR File Specification, Available at
_http://docs.oracle.com/javase/8/docs/technotes/guides/jar/jar.html_ .

 _The Common Object Request Broker: Architecture
and Specification_ (CORBA 2.3.1 specification), Available at
_http://www.omg.org/cgi-bin/doc?formal/99-10-07_ .

CORBA 2.6 - Chapter 26 - Secure
Interoperability, Available at
_http://www.omg.org/cgi-bin/doc?formal/01-12-30_ .

 _IDL To Java™ Language Mapping Specification_ ,
Available at _http://www.omg.org/cgi-bin/doc?ptc/2000-01-08_ .

 _Java™ Language To IDL Mapping Specification_ ,
Available at _http://www.omg.org/cgi-bin/doc?ptc/2000-01-06_ .

 _Interoperable Naming Service,_ Available at
_http://www.omg.org/cgi-bin/doc?ptc/00-08-07_ .

 _Transaction Service Specification_ (OTS
specification), Available at
_http://www.omg.org/cgi-bin/doc?formal/2001-11-03_ .

 _The SSL Protocol, Version 3.0._ Available at
_http://tools.ietf.org/html/rfc6101_ .

Architectural Styles and the Design of
Network-based Software Architectures (REST), R. Fielding, Ph.d
dissertation, University of California, Irvine, 2000. Available at
_http://roy.gbiv.com/pubs/dissertation/top.html_ .

Java _™_ Community Process
_SM_ 2: Process Document, Version 2.10 (March 21, 2016). Available at
_http://jcp.org/en/procedures/jcp2_ .







'''''

[.footnoteNumber]# 1.# [[a3648]]While the client is
stateless with respect to authentication, the client requires that the
server act as its proxy and maintain its login context. A reference to
the login session state is made available to the client through cookies
or URL re-writing. If SSL mutual authentication is used as the
authentication protocol, the client can manage its own authentication
context, and need not depend on references to the login session state.

[.footnoteNumber]# 2.# [[a3649]]A product instance
corresponds to a single installation of a Java EE product. A single
product instance might use multiple operating system processes, or might
support multiple host machines as part of a distributed container. In
contrast, it might be possible to run multiple instances of a product on
a single host machine, or possibly even in a single Java virtual
machine, for example, as part of a virtual hosting solution. The
transaction propagation requirement applies within a single product
instance and is independent of the number of Java virtual machines,
operating system processes, or host machines used by the product
instance.

[.footnoteNumber]# 3.# [[a3650]]For a JSP page, this
requirement applies to the _service_ method of the equivalent JSP page
Implementation Class.

[.footnoteNumber]# 4.# [[a3651]]Note that Java EE
Managed Beans are required to have access to the JNDI naming environment
of their calling component.

[.footnoteNumber]# 5.# [[a3652]]Note that the use of
interceptors defined by means of the Interceptors annotation is
supported in the absence of CDI for EJB and Managed Bean components.

[.footnoteNumber]# 6.# [[a3653]]See the JSF
specification section “JSF Managed Classes and Java EE Annotations” for
a list of these managed classes.

[.footnoteNumber]# 7.# [[a3654]]Resource and CDI
injection is supported only in JAX-RS components managed by CDI.

[.footnoteNumber]# 8.# [[a3655]]Interceptors cannot be
bound to other interceptors.

[.footnoteNumber]# 9.# [[a3656]]See the CDI
specification for requirements related to resource injection in CDI
managed beans.

[.footnoteNumber]# 10.# [[a3657]]We use this term to
refer to classes that become managed beans per the rules in the CDI
specification, thus excluding managed beans declared using the
_ManagedBean_ annotation as well as EJB session beans, both of which
would be managed beans even in the absence of CDI.

[.footnoteNumber]# 11.# [[a3658]]Interceptors cannot
be bound to decorators.

[.footnoteNumber]# 12.# [[a3659]]Connections obtained
from the same resource manager connection factory through a different
resource manager connection factory reference may be shareable.

[.footnoteNumber]# 13.# [[a3660]]Note that the
Deployer is not prohibited from overriding the resource address.

[.footnoteNumber]# 14.# [[a3661]]Client APIs only.

[.footnoteNumber]# 15.# [[a3662]]EJB entity beans and
associated EJB QL only.

[.footnoteNumber]# 16.# [[a3663]]IIOP
interoperability, including EJB 2.x and 1.x client view.

[.footnoteNumber]# 17.# [[a3664]]See
link:#a2730[See Java™ Platform,
Enterprise Edition Deployment API 1.2 Requirements (Optional)] for
details.

[.footnoteNumber]# 18.# [[a3665]]Note that a component
specification is permitted to specify an exception to this in order to
accommodate interface type dependencies—for example, the EJB
SessionContext dependency on the javax.xml.rpc.handler.MessageContext
type.

[.footnoteNumber]# 19.# [[a3666]]The FilePermission *
specifically refers to all files under the current directory.

[.footnoteNumber]# 20.# [[a3667]](For Web components
only.) It must be possible to grant FilePermission for the tempdir
provided to web components through the ServletContext regardless of its
physical location. In addition, it must be possible to grant
FilePermission for the tempdir without granting it for all files under
the current directory.

[.footnoteNumber]# 21.# [[a3668]]It must be possible
to deploy an application module such that no instances of
java.lang.RuntimePermission are granted to the components in the
application module except those with a target of loadlibrary.* for any
specific library or a target of queuePrintJob. Ideally a container would
be capable of restricting those as well, but that is not a requirement.

[.footnoteNumber]# 22.# [[a3669]]It must be possible
to deploy an application module such that no instances of
java.util.PropertyPermission are granted that allow writing any
property.
