[appendix]
[[revisionHistory]]
== Revision History
=== Changes in Final Release for EE11
* 

=== Changes in Final Release for EE10
* Updated Java SE base version to 11.
* Added basic module-info.class requirements to API artifacts.
* Added restrictions concerning where jakarta package name usage is appropriate.
* Added SecurityManager deprecation.
* Removed applet requirements.
* Refactored profile requirements to reduce base requirements in Core Profile.
* Removed requirement for Entity Beans, both Container and Bean Managed Persistence (Jakarta Enterprise Beans 4.0, Optional Features, Chapters 3 - 7)
* Removed requirement for embeddable EJB Container (Jakarta Enterprise Beans, Core Features 4.0, Chapter 17)
* Updated <<relateddocs, “Related Documents">> for the updated Specifications in Jakarta EE 10.0.

=== Changes in Final Release EE9.1
==== Editorial Changes
* Added the support for implementations to run and certify using Java SE 11.
* Clarified the optional support for CORBA and the ORB.
* Updated <<relateddocs, “Related Documents">> for the updated Specifications in Jakarta EE 9.1.
