[[a1100]]
== Service Provider Interface

The Jakarta™ EE Platform includes several technologies that are primarily
intended to be used to extend the capabilities of the Jakarta EE containers.
In addition, some Jakarta EE technologies include service provider interfaces
along with their application programming interfaces. A Jakarta EE profile may
include some or all of these facilities, as described in <<a3212, Profiles>>.

=== Jakarta™ Connectors

The Connector API defines how resource adapters
are packaged and integrated with any Jakarta EE product. Many types of
service providers can be provided using the Connector API and packaging,
including JDBC drivers, Jakarta Messaging providers, and Jakarta XML Registries
providers. All Jakarta EE products must support the Connector APIs, as specified
in the Connector specification.

The Jakarta EE Connectors specification is available at
_https://jakarta.ee/specifications/connectors_ .

=== Jakarta™ Authorization

The Jakarta Authorization specification defines the contract
between a Jakarta EE container and an authorization policy provider.

The Jakarta Authorization specification can be found at
_https://jakarta.ee/specifications/authorization_ .

=== Jakarta™ Transactions

The Jakarta Transactions defines the
_TransactionSynchronizationRegistry_ interface that is intended for use
by system level application server components such as persistence
managers, resource adapters, as well as Jakarta Enterprise Beans and Web application
components. This provides the ability to register synchronization
objects with special ordering semantics, associate resource objects with
the current transaction, get the transaction context of the current
transaction, get current transaction status, and mark the current
transaction for rollback.

The Jakarta Transaction specification is available at
_https://jakarta.ee/specifications/transactions_ .

=== Jakarta™ Persistence

Jakarta Persistence provides interfaces in the
_jakarta.persistence.spi_ package that allow a persistence provider to be
plugged into the Jakarta Persistence framework.

The Jakarta Persistence specification can be
found at _https://jakarta.ee/specifications/persistence_ .

=== Jakarta™ Mail

The Jakarta Mail specification describes how
Jakarta Mail protocol providers can be packaged and distributed so that they
can be discovered and used through the Jakarta Mail API. This allows the
Jakarta Mail API to be extended with support for new mail protocols and
mailbox formats.

The Jakarta Mail API specification is available
at _https://jakarta.ee/specifications/mail_ .
