== Service Provider Interface

The Jakarta™ EE Platform includes several technologies that are primarily
intended to be used to extend the capabilities of the Jakarta EE containers.
In addition, some Jakarta EE technologies include service provider interfaces
along with their application programming interfaces. A Jakarta EE profile may
include some or all of these facilities, as described in <<a3212, Profiles>>”.

=== Jakarta™ Connectors

The Connector API defines how resource adapters
are packaged and integrated with any Jakarta EE product. Many types of
service providers can be provided using the Connector API and packaging,
including JDBC drivers, Jakarta Messaging providers, and Jakarta XML Registries
providers. All Jakarta EE products must support the Connector APIs, as specified
in the Connector specification.

=== Jakarta™ Authorization

The Jakarta Authorization specification defines the contract
between a Jakarta EE container and an authorization policy provider.

=== Jakarta™ Transactions

The Jakarta Transactions defines the
_TransactionSynchronizationRegistry_ interface that is intended for use
by system level application server components such as persistence
managers, resource adapters, as well as Jakarta Enterprise Beans and Web application
components. This provides the ability to register synchronization
objects with special ordering semantics, associate resource objects with
the current transaction, get the transaction context of the current
transaction, get current transaction status, and mark the current
transaction for rollback.

=== Jakarta™ Persistence

Jakarta Persistence provides interfaces in the
_javax.persistence.spi_ package that allow a persistence provider to be
plugged into the Jakarta Persistence framework.

=== Jakarta™ Mail

The Jakarta Mail specification describes how
Jakarta Mail protocol providers can be packaged and distributed so that they
can be discovered and used through the Jakarta Mail API. This allows the
Jakarta Mail API to be extended with support for new mail protocols and
mailbox formats.

=== Specification documents

==== Original Java™ EE specification documents

- Java™ EE Connector Architecture: _http://jcp.org/en/jsr/detail?id=322_ 
- Java™ Authorization Service Provider Contract for Containers: _http://jcp.org/en/jsr/detail?id=115_
- Java™ Transaction API: _http://jcp.org/en/jsr/detail?id=907_
- Java™ Persistence: _http://jcp.org/en/jsr/detail?id=338_
- JavaMail™: _http://jcp.org/en/jsr/detail?id=919_

==== Jakarta EE specification documents

- Not available yet
