[[lifecycle_ee]]

== Lifecycle of contextual instances

[[biz_method_ee]]

=== Container invocations and interception in Jakarta EE

When the application invokes:

* a business method of a session bean via an enterprise bean remote or local reference,

the invocation is treated as a _business method invocation_.

When running in Jakarta EE, the container must extend the rules defined in <<biz_method>>, with:

* Invocation of Jakarta Enterprise Beans timer service timeouts by the container are not business method invocations, but are intercepted by interceptors for enterprise bean timeouts.
* Only an invocation of business method on a session enterprise bean is subject to Jakarta Enterprise Beans services such as declarative transaction management, concurrency, security and asynchronicity, as defined by the Jakarta Enterprise Beans specification.
* Additionally, invocations of message listener methods of message-driven beans during message delivery are passed through method interceptors.


[[stateful_lifecycle]]

==== Lifecycle of stateful session enterprise beans

When the `create()` method of a `Bean` object that represents a stateful session enterprise bean that is called, the container creates and returns a container-specific internal local reference to a new session enterprise bean instance. The reference must be passivation capable. This reference is not directly exposed to the application.
When the `create()` method of a `Bean` object that represents a stateful session enterprise bean that is called, the container creates and returns a container-specific internal local reference to a new session enterprise bean instance. The reference must be passivation capable. This reference is not directly exposed to the application.

Before injecting or returning a contextual instance to the application, the container transforms its internal reference into an object that implements the bean types expected by the application and delegates method invocations to the underlying stateful session enterprise bean instance. This object must be passivation capable.

When the `destroy()` method is called, and if the underlying enterprise bean was not already removed by direct invocation of a remove method by the application, the container removes the stateful session enterprise bean.
The `@PreDestroy` callback must be invoked by the container.

Note that the container performs additional work when the underlying enterprise bean is created and removed, as defined in <<injection>>

[[stateless_lifecycle]]

==== Lifecycle of stateless and singleton session enterprise beans

When the `create()` method of a `Bean` object that represents a stateless session or singleton session enterprise bean is called, the container creates and returns a container-specific internal local reference to the session enterprise bean.
This reference is not directly exposed to the application.

Before injecting or returning a contextual instance to the application, the container transforms its internal reference into an object that implements the bean types expected by the application and delegates method invocations to the underlying session enterprise bean.
This object must be passivation capable.

When the `destroy()` method is called, the container simply discards this internal reference.

Note that the container performs additional work when the underlying enterprise bean is created and removed, as defined in <<injection>>

[[resource_lifecycle]]

==== Lifecycle of resources

When the `create()` method of a `Bean` object that represents a resource is called, the container creates and returns a container-specific internal reference to the Jakarta EE component environment resource, entity manager, entity manager factory, remote enterprise bean instance or web service reference. This reference is not directly exposed to the application.

Before injecting or returning a contextual instance to the application, the container transforms its internal reference into an object that implements the bean types expected by the application and delegates method invocations to the underlying resource, entity manager, entity manager factory, remote enterprise bean instance or web service reference. This object must be passivation capable.

The container must perform ordinary Jakarta EE component environment injection upon any non-static field that functions as a resource declaration, as defined by the Jakarta EE Platform and Jakarta Annotations specifications.
The container is not required to perform Jakarta EE component environment injection upon a static field.
Portable applications should not rely upon the value of a static field that functions as a resource declaration.

References to enterprise beans and web services are always dependent scoped and a new instance must be obtained for every injection performed.

For an entity manager associated with a resource definition, it must behave as though it were injected directly using `@PersistenceContext`.

When the `destroy()` method of a bean which represents a remote stateful enterprise bean reference is called, the container will _not_ automatically destroy the enterprise bean reference. The application must explicitly call the method annotated `@Remove`. This behavior differs to that specified in <<stateful_lifecycle>> for beans which represent a local stateful enterprise bean reference
