[[packaging_deployment_ee]]

== Packaging and deployment in Jakarta EE


[[bean_archive_ee]]
=== Bean archive with Session Enterprise Beans

When running in Jakarta EE, the container must extend the rules defined in <<bean_archive_full>> with:

* An _implicit bean archive_ may also contain session enterprise beans, and
* Session enterprise bean should be considered as bean class with bean defining annotation when determining if an archive is an _implicit bean archive_.

When determining which archives are bean archives, the container must also consider:

* Enterprise bean jars or application client jars
* The `WEB-INF/classes` directory of a war

The container is not required to support application client jar bean archives.

A Jakarta EE container is required by the Jakarta EE specification to support Jakarta EE modules.

In a war, the `beans.xml` file must be named:

* `WEB-INF/beans.xml`  or `WEB-INF/classes/META-INF/beans.xml`.

If a war has a file named `beans.xml` in both the `WEB-INF` directory and in the `WEB-INF/classes/META-INF` directory, then non-portable behavior results.
Portable applications must have a `beans.xml` file in only one of the `WEB-INF` or the `WEB-INF/classes/META-INF` directories.

The following additional rules apply regarding container search for beans:

* In an application deployed as an ear, the container searches every bean archive bundled with or referenced by the ear, including bean archives bundled with or referenced by wars, enterprise bean jars and rars contained in the ear.
The bean archives might be library jars, enterprise bean jars or war `WEB-INF/classes` directories.
* In an application deployed as a war, the container searches every bean archive bundled with or referenced by the war.
The bean archives might be library jars or the `WEB-INF/classes` directory.
* In an application deployed as an enterprise bean jar, the container searches the enterprise bean jar, if it is a bean archive, and every bean archive referenced by the enterprise bean jar.
* In an application deployed as a rar, the container searches every bean archive bundled with or referenced by the rar.


[[type_bean_discovery_ee]]

=== Type and Bean discovery for Enterprise Beans

In Jakarta EE, the container automatically discovers session enterprise beans and other Jakarta EE component class supporting injection, in bean archives like it does for managed bean as defined in <<type_bean_discovery_full>>.

[[bean_discovery_steps_ee]]

==== Bean discovery in Jakarta EE

When running in Jakarta EE, the container must extend the rules defined in <<bean_discovery_steps_full>> and must also discover each session enterprise bean.

[[trimmed_bean_archive_ee]]

==== Trimmed bean archive in Jakarta EE

When running in Jakarta EE, the container must extend the rules defined in <<trimmed_bean_archive>> and must ensure that session enterprise beans are not removed from the set of discovered types.
